project:
  type: website

website:
  title: "Education 2.0"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/All-Khwarizmi
      - icon: linkedin
        href: https://www.linkedin.com/in/jason-suarez/
format:
  html:
    theme: darkly
    css: styles.css



